services:
    _defaults:
        public: '%public.services%'

    hbpf._application.manager.webhook:
        class: Hanaboso\HbPFAppStore\Model\Webhook\WebhookManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
            - '%backend_host%'

    hbpf._application.manager.application:
        class: Hanaboso\HbPFAppStore\Model\ApplicationManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.application.loader'
            - '@hbpf._application.manager.webhook'
            -
    hbpf._application.manager.statistics:
        class: Hanaboso\HbPFAppStore\Model\StatisticsManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
