services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.authorization:
        class: Hanaboso\HbPFAppStore\Loader\ApplicationLoader
        public: true
        arguments:
            - '@service_container'

    hbpf._application.handler.application:
        class: Hanaboso\HbPFAppStore\Handler\ApplicationHandler
        arguments:
            - '@hbpf._application.manager.application'
            - '@hbpf._application.manager.webhook'

    hbpf._application.handler.webhook:
        class: Hanaboso\HbPFAppStore\Handler\WebhookHandler
        arguments:
            - '@hbpf._application.manager.application'
